-- 既存テーブル削除（オプション）
DROP TABLE IF EXISTS note;
DROP TABLE IF EXISTS users;

-- テーブル作成
CREATE TABLE IF NOT EXISTS users (
    -- id BIGSERIAL PRIMARY KEY, -- PostgreSQL 方言
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- H2/標準SQL 推奨
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(60) NOT NULL
);

CREATE TABLE note (
    -- id BIGSERIAL PRIMARY KEY, -- PostgreSQL 方言
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- H2/標準SQL 推奨
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    last_edited TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sort_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_note_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 複合インデックス追加
CREATE INDEX idx_note_user_sort ON note(user_id, sort_order);